name: CI/CD Pipeline

# Define events that trigger the workflow
on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build:
    # Define the environment for the build job
    runs-on: ubuntu-latest
    
    # Steps for the build job
    steps:
      - name: Checkout code  # Check out the repository
        uses: actions/checkout@v2
        
      - name: Login to DockerHub  # Log in to DockerHub
        uses: docker/login-action@v2  # Updated DockerHub login action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # DockerHub username from secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # DockerHub token from secrets
          
      - name: Build and push Docker image  # Build and push the Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: my-image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .  # Build the Docker image
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest  # Push the Docker image to DockerHub

  test:
    # Define the environment for the test job
    runs-on: ubuntu-latest
    
    # Steps for the test job
    steps:
      - name: Checkout code  # Check out the repository
        uses: actions/checkout@v2
        
      - name: Set up Python  # Set up the Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use a specific Python version
        
      - name: Install dependencies  # Install dependencies from requirements.txt
        run: |
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from the requirements file
        
      - name: Run tests with pytest  # Run the tests with pytest
        run: pytest test.py  # Run pytest with the specific test file
