name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag, and push image to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: my-image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    needs: build
    steps:
      - name: Checkout code  # Check out the repository
        uses: actions/checkout@v2
        
      - name: Set up Python  # Set up the Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version
        
      - name: Install dependencies  # Install dependencies from requirements.txt
        run: pip install -r requirements.txt
        
      - name: Run tests with unittest  # Run tests with unittest
        run: python -m unittest test.py  # Run the specific test file with unittest